# Generated by Django 3.2 on 2021-04-27 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 8, 17, 5, 287107, tzinfo=utc)),
        ),
    ]
